"""Авторские игровые ситуации по открытым официальным материалам банков.

Разделы терминала унифицированы для игры, а не воспроизводят меню банка.
Проверка источников: 2026-09-13. Подробности и ограничения — SOURCES.md.
"""

CATEGORIES = [
    {"id": "accounts", "title": "Счета и карты", "subtitle": "Получить карту, открыть текущий счёт", "code": "А", "icon": "card"},
    {"id": "credit", "title": "Кредитные продукты", "subtitle": "Кредитка, кредит, ипотека", "code": "К", "icon": "credit"},
    {"id": "savings", "title": "Вклады и накопления", "subtitle": "Вклад или накопительный счёт", "code": "В", "icon": "savings"},
    {"id": "cash", "title": "Операции с наличными", "subtitle": "Выдать или принять деньги в кассе", "code": "Н", "icon": "cash"},
    {"id": "insurance", "title": "Страховые продукты", "subtitle": "Полис для дома, машины, поездки", "code": "С", "icon": "shield"},
    {"id": "transfers", "title": "Платежи и переводы", "subtitle": "Перевести деньги, оплатить услуги", "code": "П", "icon": "transfer"},
]

OFFICIAL_SOURCES = [
    {"id": "sber_card", "bank": "Сбер", "title": "Тарифы по СберКарте и платёжным счетам (официальный PDF)", "url": "https://cms-res-web.online.sberbank.ru/sbercard/documents/v3/TP_Sberkarta2.pdf"},
    {"id": "alfa_cards", "bank": "Альфа-Банк", "title": "Дебетовые карты: оформление и получение", "url": "https://alfabank.ru/everyday/debit-cards/"},
    {"id": "alfa_reissue", "bank": "Альфа-Банк", "title": "Выпуск, перевыпуск и блокировка карты", "url": "https://alfabank.ru/help/t/retail/debitcards/vipusk-perevipusk-i-blokirovka-karti/"},
    {"id": "alfa_current", "bank": "Альфа-Банк", "title": "Справка Альфа-Клик: открытие текущего счёта", "url": "https://click.alfabank.ru/cs/groups/public/documents/document/alfa_help10_02.html"},
    {"id": "vtb_creditcard", "bank": "ВТБ", "title": "Кредитные карты", "url": "https://www.vtb.ru/personal/karty/kreditnye/"},
    {"id": "vtb_refinance", "bank": "ВТБ", "title": "Рефинансирование кредитов", "url": "https://www.vtb.ru/personal/kredit/refinansirovanie/"},
    {"id": "vtb_mortgage", "bank": "ВТБ", "title": "Ипотека", "url": "https://www.vtb.ru/personal/ipoteka/"},
    {"id": "vtb_savings", "bank": "ВТБ", "title": "Вклады и накопительные счета", "url": "https://www.vtb.ru/personal/vklady-i-scheta/"},
    {"id": "alfa_savings", "bank": "Альфа-Банк", "title": "Накопительные продукты и получение наличных в кассе", "url": "https://alfabank.ru/make-money/"},
    {"id": "vtb_cash_deposit", "bank": "ВТБ", "title": "Пополнение дебетовой карты, в том числе через кассу", "url": "https://www.vtb.ru/articles/debetovye-karty/kak-zarabotat-na-bankovskikh-debetovykh-kartakh/"},
    {"id": "alfa_home", "bank": "Альфа-Банк", "title": "Дом под защитой", "url": "https://alfabank.ru/retail/insurance-digital/home/"},
    {"id": "sber_travel", "bank": "СберСтрахование", "title": "Страхование путешественников", "url": "https://sberbankins.ru/products/travel-online/"},
    {"id": "sber_osago", "bank": "СберСтрахование", "title": "ОСАГО", "url": "https://sberbankins.ru/products/osago/"},
    {"id": "sber_driver", "bank": "СберСтрахование", "title": "Защита водителя", "url": "https://sberbankins.ru/products/driver-protection/"},
    {"id": "vtb_transfers", "bank": "ВТБ", "title": "Платежи и переводы", "url": "https://www.vtb.ru/personal/platezhi-i-perevody/"},
    {"id": "vtb_payments", "bank": "ВТБ", "title": "Оплата услуг, счетов и квитанций", "url": "https://www.vtb.ru/personal/platezhi/"},
]

SCENARIOS = [
    {
        "id": "accounts_ready", "name": "Анна",
        "text": "Карту уже оформила. Пришло сообщение, что она готова. Хочу забрать!",
        "category": "accounts",
        "explanation": "Карта уже оформлена: её получение в игре относится к разделу «Счета и карты».",
        "source_ids": ["alfa_cards"],
    },
    {
        "id": "accounts_debit", "name": "Михаил",
        "text": "Нужна обычная дебетовая карта для покупок. Буду тратить свои деньги.",
        "category": "accounts",
        "explanation": "Оформление дебетовой карты — раздел «Счета и карты».",
        "source_ids": ["alfa_cards", "sber_card"],
    },
    {
        "id": "accounts_reissue", "name": "Полина",
        "text": "Потерянную дебетовую карту уже заблокировала. Теперь хочу заказать новую взамен.",
        "category": "accounts",
        "explanation": "Клиенту нужен перевыпуск дебетовой карты: выбираем «Счета и карты».",
        "source_ids": ["alfa_reissue"],
    },
    {
        "id": "accounts_expired", "name": "Виктор",
        "text": "Срок дебетовой карты закончился. Нужна замена, счёт хочу сохранить.",
        "category": "accounts",
        "explanation": "Замена карты по сроку действия — обслуживание карты.",
        "source_ids": ["alfa_reissue"],
    },
    {
        "id": "accounts_current", "name": "Марина",
        "text": "Хочу открыть обычный текущий счёт для повседневных расчётов.",
        "category": "accounts",
        "explanation": "Текущий счёт для расчётов относится к «Счетам и картам». Накопительный счёт — другой раздел.",
        "source_ids": ["alfa_current"],
    },
    {
        "id": "accounts_extra", "name": "Олег",
        "text": "Хочу оформить дополнительную дебетовую карту к своему счёту для супруги.",
        "category": "accounts",
        "explanation": "Дополнительная дебетовая карта — услуга раздела «Счета и карты».",
        "source_ids": ["alfa_cards", "vtb_cash_deposit"],
    },
    {
        "id": "credit_new_card", "name": "Денис",
        "text": "Хочу оформить кредитную карту. Заявку ещё не подавал.",
        "category": "credit",
        "explanation": "Новая кредитная карта — кредитный продукт, даже если в запросе есть слово «карта».",
        "source_ids": ["vtb_creditcard"],
    },
    {
        "id": "credit_consumer", "name": "Ирина",
        "text": "Хочу подать заявку на потребительский кредит для ремонта кухни.",
        "category": "credit",
        "explanation": "Заявка на заём направляется к специалисту по кредитным продуктам.",
        "source_ids": ["vtb_refinance"],
    },
    {
        "id": "credit_refinance", "name": "Роман",
        "text": "У меня кредит в другом банке. Хочу обсудить его рефинансирование.",
        "category": "credit",
        "explanation": "Рефинансирование связано с кредитным договором: нужен раздел «Кредитные продукты».",
        "source_ids": ["vtb_refinance"],
    },
    {
        "id": "credit_mortgage", "name": "Светлана",
        "text": "Планирую купить квартиру. Хочу обсудить заявку на ипотеку.",
        "category": "credit",
        "explanation": "Ипотека — жилищный кредит. В игровом терминале она входит в кредитные продукты.",
        "source_ids": ["vtb_mortgage"],
    },
    {
        "id": "credit_early", "name": "Артём",
        "text": "Нужна консультация по досрочному погашению кредита. В кассу сегодня не иду.",
        "category": "credit",
        "explanation": "Вопрос касается погашения кредитного договора, а не выдачи или приёма наличных.",
        "source_ids": ["vtb_refinance"],
    },
    {
        "id": "credit_limit", "name": "Екатерина",
        "text": "Хочу узнать, как изменить кредитный лимит по моей кредитке.",
        "category": "credit",
        "explanation": "Лимит заёмных средств относится к кредитному продукту.",
        "source_ids": ["vtb_creditcard"],
    },
    {
        "id": "savings_deposit", "name": "Алексей",
        "text": "Хочу открыть вклад на определённый срок. Деньги уже на моём счёте.",
        "category": "savings",
        "explanation": "Открытие вклада — раздел «Вклады и накопления».",
        "source_ids": ["vtb_savings"],
    },
    {
        "id": "savings_account", "name": "Дарья",
        "text": "Хочу открыть накопительный счёт и понемногу откладывать на отпуск.",
        "category": "savings",
        "explanation": "Накопительный счёт в игре относится к сбережениям, а не к текущим счетам.",
        "source_ids": ["alfa_savings"],
    },
    {
        "id": "savings_topup", "name": "Борис",
        "text": "Хочу обсудить пополнение моего вклада с другого своего счёта.",
        "category": "savings",
        "explanation": "Клиент спрашивает об обслуживании вклада: выбираем «Вклады и накопления».",
        "source_ids": ["vtb_savings"],
    },
    {
        "id": "savings_close", "name": "Наталья",
        "text": "Срок вклада подошёл к концу. Хочу закрыть его, оставив деньги на счёте.",
        "category": "savings",
        "explanation": "Закрытие вклада — операция со сбережениями; наличные клиент не получает.",
        "source_ids": ["vtb_savings"],
    },
    {
        "id": "savings_statement", "name": "Григорий",
        "text": "Мне нужна выписка именно по вкладу: хочу увидеть начисленные проценты.",
        "category": "savings",
        "explanation": "Выписка по вкладу относится к обслуживанию накоплений.",
        "source_ids": ["vtb_savings"],
    },
    {
        "id": "savings_compare", "name": "Вера",
        "text": "Хочу разобраться в разнице между вкладом и накопительным счётом.",
        "category": "savings",
        "explanation": "Оба продукта предназначены для накоплений. Нужен специалист по вкладам.",
        "source_ids": ["alfa_savings"],
    },
    {
        "id": "cash_reserved", "name": "Андрей",
        "text": "Я заранее заказал наличные. Пришёл получить их в кассе со своего счёта.",
        "category": "cash",
        "explanation": "Выдача заказанных наличных выполняется в кассе.",
        "source_ids": ["alfa_savings"],
    },
    {
        "id": "cash_withdraw", "name": "Людмила",
        "text": "Нужны наличные рубли с моего счёта. Хочу снять их у кассира.",
        "category": "cash",
        "explanation": "Клиент прямо просит выдачу наличных: нужен кассовый талон.",
        "source_ids": ["sber_card", "vtb_savings"],
    },
    {
        "id": "cash_after_deposit", "name": "Павел",
        "text": "Вклад уже закрыт, деньги на текущем счёте. Теперь хочу получить купюры в кассе.",
        "category": "cash",
        "explanation": "Действие со вкладом завершено. Текущая задача — получить наличные в кассе.",
        "source_ids": ["vtb_savings"],
    },
    {
        "id": "cash_deposit", "name": "Юлия",
        "text": "Принесла наличные рубли. Хочу внести их на свой счёт через кассу.",
        "category": "cash",
        "explanation": "Приём наличных через кассу — раздел «Операции с наличными».",
        "source_ids": ["vtb_cash_deposit"],
    },
    {
        "id": "cash_card_topup", "name": "Тимур",
        "text": "Хочу пополнить дебетовую карту купюрами именно у кассира.",
        "category": "cash",
        "explanation": "Главная операция — внесение наличных в кассе, хотя деньги идут на карту.",
        "source_ids": ["vtb_cash_deposit"],
    },
    {
        "id": "cash_gift", "name": "Оксана",
        "text": "Подарили деньги в конверте. Хочу через кассу положить их на свою карту.",
        "category": "cash",
        "explanation": "Кассир принимает купюры для пополнения счёта карты.",
        "source_ids": ["vtb_cash_deposit"],
    },
    {
        "id": "insurance_flat", "name": "Сергей",
        "text": "Хочу узнать про страховой полис для квартиры на случай залива или пожара.",
        "category": "insurance",
        "explanation": "Защита квартиры по страховому полису — страховой продукт.",
        "source_ids": ["alfa_home"],
    },
    {
        "id": "insurance_house", "name": "Татьяна",
        "text": "Хочу обсудить страховку для моего загородного дома.",
        "category": "insurance",
        "explanation": "Клиенту нужен полис страхования дома, поэтому выбираем страховые продукты.",
        "source_ids": ["alfa_home"],
    },
    {
        "id": "insurance_travel", "name": "Кирилл",
        "text": "Собираюсь в отпуск за границу. Нужна консультация по страховке путешественника.",
        "category": "insurance",
        "explanation": "Полис для поездки относится к страховым продуктам.",
        "source_ids": ["sber_travel"],
    },
    {
        "id": "insurance_osago", "name": "Елена",
        "text": "Мне нужен полис ОСАГО для автомобиля. Хочу узнать про оформление.",
        "category": "insurance",
        "explanation": "ОСАГО — страховой полис. В игре консультация направляется в страховые продукты.",
        "source_ids": ["sber_osago"],
    },
    {
        "id": "insurance_driver", "name": "Максим",
        "text": "Хочу узнать о страховании водителя от несчастного случая.",
        "category": "insurance",
        "explanation": "Вопрос о страховой защите водителя относится к страховым продуктам.",
        "source_ids": ["sber_driver"],
    },
    {
        "id": "insurance_terms", "name": "Алина",
        "text": "Перед оформлением страховки квартиры хочу выяснить, какие риски включены в полис.",
        "category": "insurance",
        "explanation": "Условия и покрытие полиса объясняет специалист по страховым продуктам.",
        "source_ids": ["alfa_home"],
    },
    {
        "id": "transfers_person", "name": "Николай",
        "text": "Хочу перевести деньги со своего счёта сестре в другой банк по реквизитам.",
        "category": "transfers",
        "explanation": "Перевод получателю в другой банк — раздел «Платежи и переводы».",
        "source_ids": ["vtb_transfers"],
    },
    {
        "id": "transfers_sbp", "name": "Ксения",
        "text": "Нужна помощь с переводом по номеру телефона через СБП.",
        "category": "transfers",
        "explanation": "СБП используется для переводов: выбираем «Платежи и переводы».",
        "source_ids": ["vtb_transfers"],
    },
    {
        "id": "transfers_utilities", "name": "Валентина",
        "text": "Хочу оплатить квитанцию за коммунальные услуги со своего счёта.",
        "category": "transfers",
        "explanation": "Оплата квитанции — платёж поставщику услуг.",
        "source_ids": ["vtb_payments"],
    },
    {
        "id": "transfers_mobile", "name": "Степан",
        "text": "Мне нужна помощь с оплатой мобильной связи банковской картой.",
        "category": "transfers",
        "explanation": "Оплата связи относится к платежам, а не к оформлению карты.",
        "source_ids": ["vtb_payments"],
    },
    {
        "id": "transfers_tuition", "name": "Лилия",
        "text": "Хочу оплатить учёбу по реквизитам из квитанции, деньги на счёте.",
        "category": "transfers",
        "explanation": "Оплата по реквизитам организации — раздел «Платежи и переводы».",
        "source_ids": ["vtb_payments"],
    },
    {
        "id": "transfers_own", "name": "Евгений",
        "text": "Хочу перевести деньги на свой текущий счёт в другом банке. Наличные не нужны.",
        "category": "transfers",
        "explanation": "Задача — безналичный перевод между банками, поэтому нужен раздел платежей и переводов.",
        "source_ids": ["vtb_transfers"],
    },
]
